Param(
  [ValidateSet("secure_linux", "native_windows_fast")]
  [string]$RuntimeMode = "native_windows_fast",
  [ValidateSet("auto", "nssm", "task", "none")]
  [string]$Hosting = "auto",
  [int]$BasePort = 19789,
  [string]$OpenClawVersion = "2026.3.22",
  [string]$ProfileName = "codex-feishu",
  [string]$ServiceName = "openclaw-codex-feishu",
  [string]$TaskName = "OpenClaw Codex Feishu",
  [switch]$NoStart,
  [switch]$SkipCodexPreflight
)

$ErrorActionPreference = "Stop"

function Write-Log([string]$Message) {
  Write-Host "[install.ps1] $Message"
}

function Require-Command([string]$Name) {
  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    throw "missing required command: $Name"
  }
}

function Require-Env([string]$Name) {
  $value = [Environment]::GetEnvironmentVariable($Name)
  if ([string]::IsNullOrWhiteSpace($value)) {
    throw "missing required env var: $Name"
  }
  return $value
}

function To-UnixPath([string]$PathValue) {
  return ($PathValue -replace "\\", "/")
}

function Set-UserEnvVar([string]$Name, [string]$Value) {
  if ([string]::IsNullOrWhiteSpace($Value)) {
    return
  }
  [Environment]::SetEnvironmentVariable($Name, $Value, "User")
}

function Ensure-EnvPersisted([hashtable]$EnvMap) {
  foreach ($entry in $EnvMap.GetEnumerator()) {
    Set-UserEnvVar -Name $entry.Key -Value $entry.Value
  }
}

function Ensure-Directory([string]$PathValue) {
  New-Item -ItemType Directory -Path $PathValue -Force | Out-Null
}

function Write-InstallHealth(
  [string]$PathValue,
  [string]$Result,
  [string]$Message,
  [string]$RuntimeModeValue,
  [string]$HostingModeValue,
  [string]$ServiceActive,
  [string]$TaskActive,
  [int]$PortValue
) {
  Ensure-Directory (Split-Path -Parent $PathValue)
  $payload = @{
    timestamp = (Get-Date).ToUniversalTime().ToString("o")
    platform = "windows"
    result = $Result
    message = $Message
    runtimeMode = $RuntimeModeValue
    hostingMode = $HostingModeValue
    serviceActive = $ServiceActive
    taskActive = $TaskActive
    basePort = $PortValue
  }
  ($payload | ConvertTo-Json -Depth 4) | Set-Content -Path $PathValue -Encoding UTF8
}

function Write-GatewayLauncherCmd(
  [string]$LauncherPath,
  [string]$RuntimeBin,
  [string]$RuntimeEntry,
  [string]$ConfigOut,
  [string]$OpenClawHome,
  [string]$OpenClawState,
  [string]$XdgConfig,
  [string]$XdgCache,
  [string]$XdgData,
  [string]$SecretsCmdPath,
  [int]$BasePortValue
) {
  $runtimeBinEscaped = $RuntimeBin.Replace('"', '""')
  $runtimeEntryEscaped = $RuntimeEntry.Replace('"', '""')
  $configOutEscaped = $ConfigOut.Replace('"', '""')
  $openClawHomeEscaped = $OpenClawHome.Replace('"', '""')
  $openClawStateEscaped = $OpenClawState.Replace('"', '""')
  $xdgConfigEscaped = $XdgConfig.Replace('"', '""')
  $xdgCacheEscaped = $XdgCache.Replace('"', '""')
  $xdgDataEscaped = $XdgData.Replace('"', '""')
  $secretsCmdEscaped = $SecretsCmdPath.Replace('"', '""')
  $runtimeBinDir = Split-Path -Parent $RuntimeBin
  $runtimeBinDirEscaped = $runtimeBinDir.Replace('"', '""')
  $basePortEscaped = [string]$BasePortValue

  $content = @(
    "@echo off",
    "setlocal",
    "set OPENCLAW_HOME=$openClawHomeEscaped",
    "set OPENCLAW_STATE_DIR=$openClawStateEscaped",
    "set OPENCLAW_CONFIG_PATH=$configOutEscaped",
    "set XDG_CONFIG_HOME=$xdgConfigEscaped",
    "set XDG_CACHE_HOME=$xdgCacheEscaped",
    "set XDG_DATA_HOME=$xdgDataEscaped",
    "if exist ""$secretsCmdEscaped"" call ""$secretsCmdEscaped""",
    "if not ""%CODEX_FEISHU_GATEWAY_TOKEN%""=="""" set OPENCLAW_GATEWAY_TOKEN=%CODEX_FEISHU_GATEWAY_TOKEN%",
    "set OPENCLAW_GATEWAY_PORT=$basePortEscaped",
    "set PATH=$runtimeBinDirEscaped;%PATH%",
    "if ""%CODEX_FEISHU_APP_ID%""=="""" echo missing CODEX_FEISHU_APP_ID & exit /b 1",
    "if ""%CODEX_FEISHU_APP_SECRET%""=="""" echo missing CODEX_FEISHU_APP_SECRET & exit /b 1",
    "node ""$runtimeEntryEscaped"" gateway run",
    "endlocal"
  ) -join "`r`n"

  Set-Content -Path $LauncherPath -Value $content -Encoding ASCII
}

function Write-SecretsCmd(
  [string]$SecretsCmdPath,
  [hashtable]$EnvMap
) {
  $lines = @("@echo off")
  foreach ($entry in $EnvMap.GetEnumerator()) {
    if ([string]::IsNullOrWhiteSpace($entry.Value)) {
      continue
    }
    $valueEscaped = ($entry.Value -replace '"', '""')
    $lines += "set $($entry.Key)=$valueEscaped"
  }
  Set-Content -Path $SecretsCmdPath -Value ($lines -join "`r`n") -Encoding ASCII
}

function Write-SecretsEnv(
  [string]$SecretsEnvPath,
  [hashtable]$EnvMap
) {
  $lines = @("# generated by scripts/install.ps1")
  foreach ($entry in $EnvMap.GetEnumerator()) {
    if ([string]::IsNullOrWhiteSpace($entry.Value)) {
      continue
    }
    $valueSanitized = ($entry.Value -replace "`r", "" -replace "`n", "")
    $lines += "$($entry.Key)=$valueSanitized"
  }
  Set-Content -Path $SecretsEnvPath -Value ($lines -join "`n") -Encoding ASCII
}

function Resolve-LatestWindowsAppsCodex() {
  try {
    $matches = Get-ChildItem -Path "C:\Program Files\WindowsApps\OpenAI.Codex_*_x64__2p2nqsd0c76g0\app\resources\codex.exe" -File -ErrorAction SilentlyContinue
    if (-not $matches) {
      return $null
    }
    return ($matches | Sort-Object LastWriteTime -Descending | Select-Object -First 1).FullName
  } catch {
    return $null
  }
}

function Resolve-CodexExecutable(
  [string]$IsolatedCodexBin
) {
  $envOverride = [Environment]::GetEnvironmentVariable("CODEX_FEISHU_CODEX_BIN")
  if (-not [string]::IsNullOrWhiteSpace($envOverride) -and (Test-Path $envOverride)) {
    return (Resolve-Path $envOverride).Path
  }

  if (Test-Path $IsolatedCodexBin) {
    return (Resolve-Path $IsolatedCodexBin).Path
  }

  $codexCommand = Get-Command codex -ErrorAction SilentlyContinue
  if ($codexCommand -and -not [string]::IsNullOrWhiteSpace($codexCommand.Source) -and (Test-Path $codexCommand.Source)) {
    return (Resolve-Path $codexCommand.Source).Path
  }

  $localAlias = Join-Path $env:LOCALAPPDATA "Microsoft\WindowsApps\codex.exe"
  if (Test-Path $localAlias) {
    return (Resolve-Path $localAlias).Path
  }

  $windowsAppsCodex = Resolve-LatestWindowsAppsCodex
  if (-not [string]::IsNullOrWhiteSpace($windowsAppsCodex) -and (Test-Path $windowsAppsCodex)) {
    return (Resolve-Path $windowsAppsCodex).Path
  }

  return $null
}

function Apply-OpenClawRuntimePatches(
  [string]$RuntimeDir
) {
  $monitorFile = Join-Path $RuntimeDir "node_modules/openclaw/dist/monitor-CPPX9Bc9.js"
  $netFile = Join-Path $RuntimeDir "node_modules/openclaw/dist/net-Dk658jWW.js"
  if (-not (Test-Path $monitorFile)) {
    throw "missing monitor file to patch: $monitorFile"
  }
  if (-not (Test-Path $netFile)) {
    throw "missing network file to patch: $netFile"
  }

  $monitorPatch = @'
const fs = require("fs");
const filePath = process.argv[2];
let source = fs.readFileSync(filePath, "utf8");

if (!source.includes("claimed by codex bridge")) {
  const needle = `\t\t} else {\n\t\t\tconst ctxPayload = await buildCtxPayloadForAgent(route.agentId, route.sessionKey, route.accountId, ctx.mentionedBot);\n\t\t\tconst identity = resolveAgentOutboundIdentity(cfg, route.agentId);`;
  const replacement = `\t\t} else {\n\t\t\tconst ctxPayload = await buildCtxPayloadForAgent(route.agentId, route.sessionKey, route.accountId, ctx.mentionedBot);\n\t\t\tconst codexBridgeClaim = globalThis.__codexFeishuBridgeClaim;\n\t\t\tif (typeof codexBridgeClaim === "function") try {\n\t\t\t\tconst claimResult = await codexBridgeClaim({\n\t\t\t\t\tchannel: "feishu",\n\t\t\t\t\taccountId: account.accountId,\n\t\t\t\t\tconversationId: ctx.chatId,\n\t\t\t\t\tparentConversationId,\n\t\t\t\t\tsenderId: ctx.senderOpenId,\n\t\t\t\t\tsenderName: ctx.senderName ?? ctx.senderOpenId,\n\t\t\t\t\tmessageId: ctx.messageId,\n\t\t\t\t\tisGroup,\n\t\t\t\t\tcontent: ctx.content,\n\t\t\t\t\tbody: ctx.content,\n\t\t\t\t\tbodyForAgent: ctx.content\n\t\t\t\t}, {\n\t\t\t\t\tchannelId: "feishu",\n\t\t\t\t\taccountId: account.accountId,\n\t\t\t\t\tconversationId: ctx.chatId,\n\t\t\t\t\tparentConversationId,\n\t\t\t\t\tsenderId: ctx.senderOpenId,\n\t\t\t\t\tmessageId: ctx.messageId\n\t\t\t\t});\n\t\t\t\tif (claimResult?.handled) {\n\t\t\t\t\tlog(\`feishu[\${account.accountId}]: claimed by codex bridge (message=\${ctx.messageId})\`);\n\t\t\t\t\tif (isGroup && historyKey && chatHistories) clearHistoryEntriesIfEnabled({\n\t\t\t\t\t\thistoryMap: chatHistories,\n\t\t\t\t\t\thistoryKey,\n\t\t\t\t\t\tlimit: historyLimit\n\t\t\t\t\t});\n\t\t\t\t\treturn;\n\t\t\t\t}\n\t\t\t} catch (err) {\n\t\t\t\tlog(\`feishu[\${account.accountId}]: codex bridge claim failed: \${String(err)}\`);\n\t\t\t}\n\t\t\tconst identity = resolveAgentOutboundIdentity(cfg, route.agentId);`;
  if (!source.includes(needle)) {
    console.error(`patch needle not found in ${filePath}`);
    process.exit(1);
  }
  source = source.replace(needle, replacement);
  fs.writeFileSync(filePath, source);
}
'@
  $monitorPatch | node - $monitorFile | Out-Null

  $netPatch = @'
const fs = require("fs");
const filePath = process.argv[2];
let source = fs.readFileSync(filePath, "utf8");

const loopbackNeedle = `\tif (mode === "loopback") {\n\t\tif (await canBindToHost("127.0.0.1")) return "127.0.0.1";\n\t\treturn "0.0.0.0";\n\t}`;
const loopbackReplacement = `\tif (mode === "loopback") return "127.0.0.1";`;
if (source.includes(loopbackNeedle)) {
  source = source.replace(loopbackNeedle, loopbackReplacement);
}

const customNeedle = `\tif (mode === "custom") {\n\t\tconst host = customHost?.trim();\n\t\tif (!host) return "0.0.0.0";\n\t\tif (isValidIPv4(host) && await canBindToHost(host)) return host;\n\t\treturn "0.0.0.0";\n\t}`;
const customReplacement = `\tif (mode === "custom") {\n\t\tconst host = customHost?.trim();\n\t\tif (!host) return "0.0.0.0";\n\t\tif (isValidIPv4(host)) return host;\n\t\treturn "0.0.0.0";\n\t}`;
if (source.includes(customNeedle)) {
  source = source.replace(customNeedle, customReplacement);
}

fs.writeFileSync(filePath, source);
'@
  $netPatch | node - $netFile | Out-Null
  Write-Log "applied isolated runtime patches in $monitorFile and $netFile"
}

function Register-WithNssm(
  [string]$LauncherPath,
  [string]$ServiceNameValue,
  [string]$WorkingDir,
  [bool]$StartNow
) {
  $nssm = Get-Command nssm -ErrorAction SilentlyContinue
  if (-not $nssm) {
    return $false
  }

  Write-Log "registering Windows service via NSSM: $ServiceNameValue"
  & $nssm.Source status $ServiceNameValue | Out-Null
  if ($LASTEXITCODE -ne 0) {
    & $nssm.Source install $ServiceNameValue $LauncherPath | Out-Host
  }
  & $nssm.Source set $ServiceNameValue AppDirectory $WorkingDir | Out-Host
  & $nssm.Source set $ServiceNameValue DisplayName "OpenClaw Codex Feishu" | Out-Host
  & $nssm.Source set $ServiceNameValue Description "Codex Feishu bridge gateway" | Out-Host
  & $nssm.Source set $ServiceNameValue Start SERVICE_AUTO_START | Out-Host

  if ($StartNow) {
    & $nssm.Source start $ServiceNameValue | Out-Host
  }
  return $true
}

function Register-WithScheduledTask(
  [string]$LauncherPath,
  [string]$TaskNameValue,
  [bool]$StartNow
) {
  Write-Log "registering logon task: $TaskNameValue"
  $action = New-ScheduledTaskAction -Execute $LauncherPath
  $trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
  $principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive -RunLevel Limited
  $settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit (New-TimeSpan -Hours 0) -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries
  Register-ScheduledTask -TaskName $TaskNameValue -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Force | Out-Null
  if ($StartNow) {
    Start-ScheduledTask -TaskName $TaskNameValue
  }
}

$isWindowsHost = $false
if (Get-Variable -Name IsWindows -ErrorAction SilentlyContinue) {
  $isWindowsHost = [bool]$IsWindows
} else {
  $isWindowsHost = [System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform(
    [System.Runtime.InteropServices.OSPlatform]::Windows
  )
}
if (-not $isWindowsHost) {
  throw "scripts/install.ps1 must run on Windows."
}

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$configTemplate = Join-Path $repoRoot "config/openclaw.codex-feishu.json5"
$runtimeDir = Join-Path $repoRoot ".runtime/openclaw-$OpenClawVersion"
$isolatedRoot = Join-Path $repoRoot ".isolated/$ProfileName"
$openclawHome = Join-Path $isolatedRoot "home"
$stateDir = Join-Path $isolatedRoot "state"
$xdgRoot = Join-Path $isolatedRoot "xdg"
$xdgConfig = Join-Path $xdgRoot "config"
$xdgCache = Join-Path $xdgRoot "cache"
$xdgData = Join-Path $xdgRoot "data"
$workspaceDir = Join-Path $repoRoot "workspaces/$ProfileName"
$configOut = Join-Path $stateDir "openclaw.codex-feishu.windows.json5"
$launcherCmd = Join-Path $stateDir "openclaw-gateway-run.cmd"
$secretsCmd = Join-Path $stateDir "openclaw-secrets.cmd"
$secretsEnv = Join-Path $stateDir "openclaw-codex-feishu.secrets.env"
$installHealthPath = Join-Path $stateDir "install-health.json"
$gatewayTokenEnv = "CODEX_FEISHU_GATEWAY_TOKEN"
$appIdEnv = "CODEX_FEISHU_APP_ID"
$appSecretEnv = "CODEX_FEISHU_APP_SECRET"
$modelApiEnv = "CODEXZH_API_KEY"
$modelProvider = "codexzh"
$modelId = "gpt-5.4"
$modelBaseUrl = "https://api.codexzh.com/v1"
$feishuDomain = "feishu"
$defaultCwd = To-UnixPath $HOME
$authJsonPath = "$defaultCwd/.codex/auth.json"
$configTomlPath = "$defaultCwd/.codex/config.toml"
$effectiveHostingMode = "none"
$serviceActive = "unknown"
$taskActive = "unknown"

Require-Command "node"
Require-Command "npm"

$appId = Require-Env $appIdEnv
$appSecret = Require-Env $appSecretEnv
$gatewayToken = [Environment]::GetEnvironmentVariable($gatewayTokenEnv)
$modelApiKey = [Environment]::GetEnvironmentVariable($modelApiEnv)

Write-Log "installing pinned openclaw runtime into $runtimeDir"
Ensure-Directory $runtimeDir
npm install --prefix $runtimeDir "openclaw@$OpenClawVersion" | Out-Host

$runtimeBin = Join-Path $runtimeDir "node_modules/.bin/openclaw.cmd"
$runtimeEntry = Join-Path $runtimeDir "node_modules/openclaw/openclaw.mjs"
$isolatedCodexBin = Join-Path $repoRoot ".runtime/codex.exe"
if (-not (Test-Path $runtimeBin)) {
  throw "missing openclaw runtime binary: $runtimeBin"
}
if (-not (Test-Path $runtimeEntry)) {
  throw "missing openclaw runtime entry: $runtimeEntry"
}

Apply-OpenClawRuntimePatches -RuntimeDir $runtimeDir

$resolvedCodexSource = Resolve-CodexExecutable -IsolatedCodexBin $isolatedCodexBin
if ([string]::IsNullOrWhiteSpace($resolvedCodexSource)) {
  throw "failed to resolve codex executable. Set CODEX_FEISHU_CODEX_BIN or install codex CLI first."
}

if ((Test-Path $resolvedCodexSource) -and ((Resolve-Path $resolvedCodexSource).Path -ne $isolatedCodexBin)) {
  try {
    Copy-Item -LiteralPath $resolvedCodexSource -Destination $isolatedCodexBin -Force
  } catch {
    Write-Log "warning: failed to mirror codex binary into $isolatedCodexBin, fallback to source path: $resolvedCodexSource"
  }
}

$codexCheckBin = if (Test-Path $isolatedCodexBin) { $isolatedCodexBin } else { $resolvedCodexSource }

if ($SkipCodexPreflight.IsPresent) {
  Write-Log "preflight: skip codex cli check (--SkipCodexPreflight)"
} else {
  Write-Log "preflight: verify codex cli is callable via $codexCheckBin"
  $codexVersion = (& $codexCheckBin --version) 2>&1
  if ($LASTEXITCODE -ne 0) {
    throw "codex --version failed via ${codexCheckBin}: $codexVersion"
  }
}

Write-Log "preflight: generate isolated config and launcher"
Ensure-Directory $openclawHome
Ensure-Directory $stateDir
Ensure-Directory $xdgConfig
Ensure-Directory $xdgCache
Ensure-Directory $xdgData
Ensure-Directory $workspaceDir

$template = Get-Content -Path $configTemplate -Raw
$replacement = @{
  "__BASE_PORT__" = "$BasePort"
  "__REPO_ROOT__" = (To-UnixPath $repoRoot)
  "__STATE_DIR__" = (To-UnixPath $stateDir)
  "__WORKSPACE_DIR__" = (To-UnixPath $workspaceDir)
  "__FEISHU_DOMAIN__" = $feishuDomain
  "__GATEWAY_TOKEN_ENV_VAR__" = $gatewayTokenEnv
  "__APP_ID_VALUE__" = $appId
  "__APP_SECRET_ENV_VAR__" = $appSecretEnv
  "__MODEL_PROVIDER_ID__" = $modelProvider
  "__MODEL_ID__" = $modelId
  "__MODEL_BASE_URL__" = $modelBaseUrl
  "__MODEL_API_ENV_VAR__" = $modelApiEnv
  "__RUNTIME_MODE__" = $RuntimeMode
  "__DEFAULT_CWD__" = $defaultCwd
  "__AUTH_JSON_PATH__" = $authJsonPath
  "__CONFIG_TOML_PATH__" = $configTomlPath
}

foreach ($key in $replacement.Keys) {
  $template = $template.Replace($key, $replacement[$key])
}
$codexBinResolvedPath = if (Test-Path $isolatedCodexBin) { $isolatedCodexBin } else { $codexCheckBin }
$codexBinForConfig = To-UnixPath $codexBinResolvedPath
$template = $template.Replace('codexBin: "codex",', "codexBin: `"$codexBinForConfig`",")
Set-Content -Path $configOut -Value $template -Encoding UTF8

Write-SecretsCmd -SecretsCmdPath $secretsCmd -EnvMap @{
  $appIdEnv = $appId
  $appSecretEnv = $appSecret
  $gatewayTokenEnv = $gatewayToken
  $modelApiEnv = $modelApiKey
}
Write-SecretsEnv -SecretsEnvPath $secretsEnv -EnvMap @{
  $appIdEnv = $appId
  $appSecretEnv = $appSecret
  $gatewayTokenEnv = $gatewayToken
  $modelApiEnv = $modelApiKey
}

Write-GatewayLauncherCmd -LauncherPath $launcherCmd -RuntimeBin $runtimeBin -RuntimeEntry $runtimeEntry -ConfigOut $configOut -OpenClawHome $openclawHome -OpenClawState $stateDir -XdgConfig $xdgConfig -XdgCache $xdgCache -XdgData $xdgData -SecretsCmdPath $secretsCmd -BasePortValue $BasePort

Write-Log "persisting required env vars in User scope"
Ensure-EnvPersisted @{
  $appIdEnv = $appId
  $appSecretEnv = $appSecret
  $gatewayTokenEnv = $gatewayToken
  $modelApiEnv = $modelApiKey
}

$startNow = -not $NoStart.IsPresent
switch ($Hosting) {
  "none" {
    $effectiveHostingMode = "none"
    Write-Log "hosting registration skipped (--Hosting none)"
  }
  "nssm" {
    if (-not (Register-WithNssm -LauncherPath $launcherCmd -ServiceNameValue $ServiceName -WorkingDir $repoRoot -StartNow:$startNow)) {
      throw "hosting=nssm requested, but nssm is not installed"
    }
    $effectiveHostingMode = "nssm"
  }
  "task" {
    Register-WithScheduledTask -LauncherPath $launcherCmd -TaskNameValue $TaskName -StartNow:$startNow
    $effectiveHostingMode = "task"
  }
  "auto" {
    $registered = Register-WithNssm -LauncherPath $launcherCmd -ServiceNameValue $ServiceName -WorkingDir $repoRoot -StartNow:$startNow
    if (-not $registered) {
      Write-Log "NSSM not found, fallback to scheduled task hosting."
      Register-WithScheduledTask -LauncherPath $launcherCmd -TaskNameValue $TaskName -StartNow:$startNow
      $effectiveHostingMode = "task"
    } else {
      $effectiveHostingMode = "nssm"
    }
  }
}

if ($effectiveHostingMode -eq "nssm") {
  $nssm = Get-Command nssm -ErrorAction SilentlyContinue
  if ($nssm) {
    $nssmStatus = (& $nssm.Source status $ServiceName) 2>&1
    if ($nssmStatus -match "SERVICE_RUNNING") {
      $serviceActive = "yes"
    } else {
      $serviceActive = "no"
    }
  }
}
if ($effectiveHostingMode -eq "task") {
  try {
    $task = Get-ScheduledTask -TaskName $TaskName -ErrorAction Stop
    if ($task.State -in @("Running", "Ready")) {
      $taskActive = "yes"
    } else {
      $taskActive = "no"
    }
  } catch {
    $taskActive = "no"
  }
}

Write-InstallHealth -PathValue $installHealthPath -Result "ok" -Message "install_completed" -RuntimeModeValue $RuntimeMode -HostingModeValue $effectiveHostingMode -ServiceActive $serviceActive -TaskActive $taskActive -PortValue $BasePort

Write-Log "done"
Write-Host ""
Write-Host "Config generated: $configOut"
Write-Host "Runtime mode: $RuntimeMode"
Write-Host "Hosting mode: $effectiveHostingMode"
Write-Host "Launcher: $launcherCmd"
Write-Host "Install health: $installHealthPath"
Write-Host ""
Write-Host "Manual foreground fallback:"
Write-Host "`"$launcherCmd`""
Write-Host ""
Write-Host "Health check after startup:"
Write-Host "/codex doctor"
